---
- name: Starting chiral docker
  docker_container:
    hostname: chiral
    name: chiral
    image: chiral:0.2.0-dev.0-x86_64
    state: started
    interactive: yes
    tty: yes
    published_ports:
      - "{{ host_port_ssh }}:22"
      - "{{ host_port_http }}:80"
      - "{{ host_port_https }}:443"
    volumes:
      - "{{ host_p4_bin_mnt_root }}"/perforce-data:/opt/perforce/perforce-data
      - "{{ host_p4_bin_mnt_root }}"/dbs:/opt/perforce/dbs
  register: x
  vars:
    ansible_python_interpreter: "{{ host_env_python }}"

- name: Logger
  debug:
    var: x.container.NetworkSettings.IPAddress
