FROM rockylinux:8.5

WORKDIR /
COPY ./repofile/* /etc/yum.repos.d
ENV TZ=America/Los_Angeles

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && PERFORCE_GPGKEY_SUM=cfd3de702b06cdc904fb17604767d6c484bfc54d7befef23a669a641816d42bd \
    && curl -fsSL https://package.perforce.com/perforce.pubkey | sed '/^Version/d' > /etc/pki/rpm-gpg/RPM-GPG-KEY-PERFORCE \
    && echo "$PERFORCE_GPGKEY_SUM  /etc/pki/rpm-gpg/RPM-GPG-KEY-PERFORCE" | sha256sum -c --strict - \
    && dnf -y install \
	helix-p4d \
	iproute \
	man \
	mlocate \
	openssh-clients \
	openssh-server \
	passwd \
	procps \
	procps-ng \
	python3 \
	sudo \
	tree \
	vim \
	&& dnf clean all && rm -rf /var/cache/dnf \
	&& ssh-keygen -t rsa -b 4096 -N '' -f ~/.ssh/id_rsa \
	&& ssh-keygen -A \
	&& echo docker | passwd root --stdin 

COPY ./authorized_keys /root/.ssh/authorized_keys

CMD /usr/sbin/sshd ; /usr/bin/bash
