version: '3'
services:
  p4:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - /Volumes/RAVAGE/data/Perforce/perforce-data:/opt/perforce/perforce-data
      - /Volumes/RAVAGE/data/Perforce/dbs:/opt/perforce/dbs
      - /Volumes/RAVAGE/data/Perforce/p4dctl.conf.d:/etc/perforce/p4dctl.conf.d
    environment:
      - P4PORT=ssl:1666
      - P4ROOT=/opt/perforce/perforce-data
      - P4USER=perforce
      - P4SSLDIR=/opt/perforce/tls
    ports:
      - "2222:22"
      - "8080:80"
      - "443:443"
      - "1666:1666"
