---
- name: Starting HelixCore docker
  docker_container:
    name: helixcore
    image: chiral:0.2.0-dev.0-x86_64
    state: started
    interactive: yes
    tty: yes
    published_ports:
      - "2222:22"
      - "8080:80"
      - "4433:443"
  register: x
  vars:
    ansible_python_interpreter: /usr/local/Caskroom/miniconda/base/envs/chiral-py392/bin/python3

- name: Logger
  debug:
    var: x.container.NetworkSettings.IPAddress

# - name: Update Container IP address in hosts.yaml
#   lineinfile:
#     path: "{{ playbook_dir }}/hosts.yaml"
#     regexp: '^(\s*)ansible_host: 11.22.33.XXX'
#     line: '\1ansible_host: {{ x.container.NetworkSettings.IPAddress }}'
#     state: present
#     backrefs: yes
