---
- name: Add IP address of all hosts to all /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    regexp: '.*{{ item }}$'
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"
